# Use the official Node.js base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Expose port 8000 for the application
EXPOSE 8000

# Command to start the Node.js server
CMD ["npm", "start" ]
